apiVersion: v1
kind: Service
metadata:
  name: messaging-app
  labels:
    app: messaging-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    current: "blue"
spec:
  type: ClusterIP
  selector:
    app: messaging-app
    version: blue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
---
# Ingress for blue-green routing
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: messaging-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: messaging-app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: messaging-app
            port:
              name: http
              port: 8080
      - path: /green
        pathType: Prefix
        backend:
          service:
            name: messaging-app
            port:
              name: http
              port: 8080
      - path: /blue
        pathType: Prefix
        backend:
          service:
            name: messaging-app
            port:
              name: http
              port: 8080